// Campo del formulario -> token visible en el preview
export const SCROLL_ANCHORS: Record<string, string> = {
  furnished: "CLAUSULA_MOBILIARIO",
  includesUtilities: "BLOQUE_SUMINISTROS",
  petsAllowed: "BLOQUE_MASCOTAS",
  additionalDeposit: "BLOQUE_DEPOSITO_ADICIONAL",
  hasGuarantors: "BLOQUE_AVALISTAS",
  landlordIdType: "BLOQUE_PARTE_ARRENDADOR",
  landlordType: "BLOQUE_PARTE_ARRENDADOR",
  landlordSigner: "BLOQUE_PARTE_ARRENDADOR",
  landlordName: "BLOQUE_PARTE_ARRENDADOR",
  landlordId: "BLOQUE_PARTE_ARRENDADOR",
  landlordAddress: "BLOQUE_PARTE_ARRENDADOR",
  tenantIdType: "BLOQUE_PARTE_ARRENDATARIO",
  tenantType: "BLOQUE_PARTE_ARRENDATARIO",
  tenantSigner: "BLOQUE_PARTE_ARRENDATARIO",
  tenantName: "BLOQUE_PARTE_ARRENDATARIO",
  tenantId: "BLOQUE_PARTE_ARRENDATARIO",
  numTenants: "CLAUSULA_SOLIDARIDAD",
  coTenant2Name: "BLOQUE_COTENANTS",
  coTenant2Type: "BLOQUE_COTENANTS",
  coTenant2IdType: "BLOQUE_COTENANTS",
  coTenant2Id: "BLOQUE_COTENANTS",
  coTenant3Name: "BLOQUE_COTENANTS",
  coTenant3Type: "BLOQUE_COTENANTS",
  coTenant3IdType: "BLOQUE_COTENANTS",
  coTenant3Id: "BLOQUE_COTENANTS",
  contractLocation: "contractLocation",
  contractDate: "contractDate",
  availabilityDate: "availabilityDate",
  monthlyRent: "monthlyRent",
  paymentMethod: "paymentMethod",
  bankName: "bankName",
  bankIban: "bankIban",
  accountHolder: "accountHolder",
  propertyAddress: "propertyAddress",
  propertyReference: "propertyReference",
  propertySize: "propertySize",
  propertyDescription: "propertyDescription",
};

export const getAnchorKey = (id: string) => SCROLL_ANCHORS[id] || id;
